### ISSUE TITLE
Can't run on Windows 10

### ISSUE THREAD

**Issue by bzuillsmith** [wqweto/UMMM#13]
I get this error trying to run this on Windows 10.

    This version of <pathToFolder>\UMMM.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by wqweto** [comment]
Which version of Win10 you are testing on? Try `ver` in command prompt.

Just tested [release 1.0.12](https://github.com/wqweto/UMMM/releases/download/1.0.12/UMMM.exe) on `Microsoft Windows [Version 10.0.14393]` and seems to work.

**Comment by bzuillsmith** [comment]
I debugged it in VB6 and it was failing [here](https://github.com/wqweto/UMMM/blob/ce74cf39aaef41e5838985b0ef203dbd2a7e05d7/Src/mdUmmm.bas#L247). I had the wrong file path in the ```Identity``` line and it was failing on that call. For some reason, that made the OS think the program was not supported I guess. Perhaps adding a ```m_oFSO.FileExists(sFile)``` check would help. I'm not quite sure where the best place to do that would be though and if it would just be a warning or should cause the whole thing to fail.

**Comment by wqweto** [comment]
Yes, a simple `FileExists` sanity check will fix this.

**Comment by Videogamer555** [comment]
It says it can't run due to incompatibility with 64bit versions of Windows. That only happens when trying to run a 16bit program. It seems the author of this program has been using a 16bit version of VB running on a 32bit or 16bit version of Windows, as his development environment. The result is a 16bit EXE file is being compiled.

I politely now ask that the creator of this software recompile it on a 32bit version of VB, so that I will actually be able to run this program.

**Comment by wqweto** [comment]
I just removed UMMM executable from the source repo. It was never meant to be there, surely an error on my part. (All the time repo's CRLF translation corrupted the binary anyway)

FYI, the official way to distribute executables on github is through [`Releases` tab](https://github.com/wqweto/UMMM/releases) of the repo. That's where I upload compiled binaries every time UMMM version is bumped.
